// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/mock_teleprompter_service.go -package=mocks -source=types.go -mock_names Service=MockTeleprompterService Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTeleprompterService is a mock of Service interface.
type MockTeleprompterService struct {
	ctrl     *gomock.Controller
	recorder *MockTeleprompterServiceMockRecorder
	isgomock struct{}
}

// MockTeleprompterServiceMockRecorder is the mock recorder for MockTeleprompterService.
type MockTeleprompterServiceMockRecorder struct {
	mock *MockTeleprompterService
}

// NewMockTeleprompterService creates a new mock instance.
func NewMockTeleprompterService(ctrl *gomock.Controller) *MockTeleprompterService {
	mock := &MockTeleprompterService{ctrl: ctrl}
	mock.recorder = &MockTeleprompterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeleprompterService) EXPECT() *MockTeleprompterServiceMockRecorder {
	return m.recorder
}

// Display mocks base method.
func (m *MockTeleprompterService) Display(text string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Display", text)
}

// Display indicates an expected call of Display.
func (mr *MockTeleprompterServiceMockRecorder) Display(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Display", reflect.TypeOf((*MockTeleprompterService)(nil).Display), text)
}

// Toggle mocks base method.
func (m *MockTeleprompterService) Toggle() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Toggle")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Toggle indicates an expected call of Toggle.
func (mr *MockTeleprompterServiceMockRecorder) Toggle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Toggle", reflect.TypeOf((*MockTeleprompterService)(nil).Toggle))
}
