// Code generated by MockGen. DO NOT EDIT.
// Source: src/adapters/ai/types.go
//
// Generated by this command:
//
//	mockgen -source=src/adapters/ai/types.go -destination=tests/mocks/mock_ai_processor.go -package=mocks -mock_names Processor=MockProcessor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	anthropic "github.com/anthropics/anthropic-sdk-go"
	option "github.com/anthropics/anthropic-sdk-go/option"
	ai "github.com/vdyalex/lens-daemon/src/adapters/ai"
	gomock "go.uber.org/mock/gomock"
)

// MockMessagesService is a mock of MessagesService interface.
type MockMessagesService struct {
	ctrl     *gomock.Controller
	recorder *MockMessagesServiceMockRecorder
	isgomock struct{}
}

// MockMessagesServiceMockRecorder is the mock recorder for MockMessagesService.
type MockMessagesServiceMockRecorder struct {
	mock *MockMessagesService
}

// NewMockMessagesService creates a new mock instance.
func NewMockMessagesService(ctrl *gomock.Controller) *MockMessagesService {
	mock := &MockMessagesService{ctrl: ctrl}
	mock.recorder = &MockMessagesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagesService) EXPECT() *MockMessagesServiceMockRecorder {
	return m.recorder
}

// New mocks base method.
func (m *MockMessagesService) New(ctx context.Context, params anthropic.MessageNewParams, opts ...option.RequestOption) (*anthropic.Message, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, params}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "New", varargs...)
	ret0, _ := ret[0].(*anthropic.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// New indicates an expected call of New.
func (mr *MockMessagesServiceMockRecorder) New(ctx, params any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, params}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "New", reflect.TypeOf((*MockMessagesService)(nil).New), varargs...)
}

// MockProcessor is a mock of Processor interface.
type MockProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockProcessorMockRecorder
	isgomock struct{}
}

// MockProcessorMockRecorder is the mock recorder for MockProcessor.
type MockProcessorMockRecorder struct {
	mock *MockProcessor
}

// NewMockProcessor creates a new mock instance.
func NewMockProcessor(ctrl *gomock.Controller) *MockProcessor {
	mock := &MockProcessor{ctrl: ctrl}
	mock.recorder = &MockProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessor) EXPECT() *MockProcessorMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockProcessor) Process(ctx context.Context, text string) (ai.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", ctx, text)
	ret0, _ := ret[0].(ai.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Process indicates an expected call of Process.
func (mr *MockProcessorMockRecorder) Process(ctx, text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockProcessor)(nil).Process), ctx, text)
}
