// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vdyalex/lens-daemon/src/modules/capturer (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination ../../../tests/mocks/mock_capturer_service.go -package mocks -mock_names Service=MockCapturerService . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	image "image"
	reflect "reflect"

	capturer "github.com/vdyalex/lens-daemon/src/modules/capturer"
	gomock "go.uber.org/mock/gomock"
)

// MockCapturerService is a mock of Service interface.
type MockCapturerService struct {
	ctrl     *gomock.Controller
	recorder *MockCapturerServiceMockRecorder
	isgomock struct{}
}

// MockCapturerServiceMockRecorder is the mock recorder for MockCapturerService.
type MockCapturerServiceMockRecorder struct {
	mock *MockCapturerService
}

// NewMockCapturerService creates a new mock instance.
func NewMockCapturerService(ctrl *gomock.Controller) *MockCapturerService {
	mock := &MockCapturerService{ctrl: ctrl}
	mock.recorder = &MockCapturerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCapturerService) EXPECT() *MockCapturerServiceMockRecorder {
	return m.recorder
}

// CaptureCenter mocks base method.
func (m *MockCapturerService) CaptureCenter(window *capturer.WindowInfo, bounds *image.Rectangle) (*image.RGBA, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CaptureCenter", window, bounds)
	ret0, _ := ret[0].(*image.RGBA)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CaptureCenter indicates an expected call of CaptureCenter.
func (mr *MockCapturerServiceMockRecorder) CaptureCenter(window, bounds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CaptureCenter", reflect.TypeOf((*MockCapturerService)(nil).CaptureCenter), window, bounds)
}

// ForegroundWindow mocks base method.
func (m *MockCapturerService) ForegroundWindow(ctx context.Context) (*capturer.WindowInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForegroundWindow", ctx)
	ret0, _ := ret[0].(*capturer.WindowInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ForegroundWindow indicates an expected call of ForegroundWindow.
func (mr *MockCapturerServiceMockRecorder) ForegroundWindow(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForegroundWindow", reflect.TypeOf((*MockCapturerService)(nil).ForegroundWindow), ctx)
}
