// Code generated by MockGen. DO NOT EDIT.
// Source: types.go
//
// Generated by this command:
//
//	mockgen -destination=../../../tests/mocks/mock_listener_service.go -package=mocks -source=types.go -mock_names Service=MockListenerService Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	slog "log/slog"
	reflect "reflect"
	time "time"

	listener "github.com/vdyalex/lens-daemon/src/modules/listener"
	gomock "go.uber.org/mock/gomock"
)

// MockListenerService is a mock of Service interface.
type MockListenerService struct {
	ctrl     *gomock.Controller
	recorder *MockListenerServiceMockRecorder
	isgomock struct{}
}

// MockListenerServiceMockRecorder is the mock recorder for MockListenerService.
type MockListenerServiceMockRecorder struct {
	mock *MockListenerService
}

// NewMockListenerService creates a new mock instance.
func NewMockListenerService(ctrl *gomock.Controller) *MockListenerService {
	mock := &MockListenerService{ctrl: ctrl}
	mock.recorder = &MockListenerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockListenerService) EXPECT() *MockListenerServiceMockRecorder {
	return m.recorder
}

// Listen mocks base method.
func (m *MockListenerService) Listen(ctx context.Context, logger *slog.Logger, pollInterval time.Duration, triggerKeycode, boundsKeycode, toggleKeycode int) (*listener.Channels, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Listen", ctx, logger, pollInterval, triggerKeycode, boundsKeycode, toggleKeycode)
	ret0, _ := ret[0].(*listener.Channels)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Listen indicates an expected call of Listen.
func (mr *MockListenerServiceMockRecorder) Listen(ctx, logger, pollInterval, triggerKeycode, boundsKeycode, toggleKeycode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Listen", reflect.TypeOf((*MockListenerService)(nil).Listen), ctx, logger, pollInterval, triggerKeycode, boundsKeycode, toggleKeycode)
}
