// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vdyalex/lens-daemon/src/modules/extractor (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination ../../../tests/mocks/mock_extractor_service.go -package mocks -mock_names Service=MockExtractorService . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	image "image"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockExtractorService is a mock of Service interface.
type MockExtractorService struct {
	ctrl     *gomock.Controller
	recorder *MockExtractorServiceMockRecorder
	isgomock struct{}
}

// MockExtractorServiceMockRecorder is the mock recorder for MockExtractorService.
type MockExtractorServiceMockRecorder struct {
	mock *MockExtractorService
}

// NewMockExtractorService creates a new mock instance.
func NewMockExtractorService(ctrl *gomock.Controller) *MockExtractorService {
	mock := &MockExtractorService{ctrl: ctrl}
	mock.recorder = &MockExtractorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExtractorService) EXPECT() *MockExtractorServiceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockExtractorService) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockExtractorServiceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockExtractorService)(nil).Close))
}

// Extract mocks base method.
func (m *MockExtractorService) Extract(img *image.RGBA) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", img)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockExtractorServiceMockRecorder) Extract(img any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockExtractorService)(nil).Extract), img)
}
