// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vdyalex/lens-daemon/src/adapters/im/poller (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination ../../../../tests/mocks/mock_poller_service.go -package mocks -mock_names Service=MockPollerService . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPollerService is a mock of Service interface.
type MockPollerService struct {
	ctrl     *gomock.Controller
	recorder *MockPollerServiceMockRecorder
	isgomock struct{}
}

// MockPollerServiceMockRecorder is the mock recorder for MockPollerService.
type MockPollerServiceMockRecorder struct {
	mock *MockPollerService
}

// NewMockPollerService creates a new mock instance.
func NewMockPollerService(ctrl *gomock.Controller) *MockPollerService {
	mock := &MockPollerService{ctrl: ctrl}
	mock.recorder = &MockPollerServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPollerService) EXPECT() *MockPollerServiceMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockPollerService) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockPollerServiceMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPollerService)(nil).Run), ctx)
}
